when:
  and:
    - equal: [main, << pipeline.git.branch >>]
    - not: << pipeline.parameters.api_triggered >>
jobs:
  - bump_version:
      context:
        - mattermost
      prepare_delivery: false

  - build_web:
      matrix:
        parameters:
          build_config_name: [integreat-test-cms, malte-test-cms, aschaffenburg, obdach]
      context:
        - mattermost
      requires:
        - bump_version
  - deliver_web:
      context:
        - mattermost
      delivery: webnext
      requires:
        - build_web
