when:
  and:
    - << pipeline.parameters.api_triggered >>
    - equal: [<< pipeline.parameters.workflow_type >>, native_production_delivery]
jobs:
  - bump_version:
      context:
        - mattermost
        - deliverino
      prepare_delivery: true

  - check:
      context:
        - mattermost

  - build_android:
      name: build_android_<< matrix.build_config_name >>
      matrix:
        parameters:
          build_config_name: [integreat-e2e, integreat, malte, aschaffenburg]
      context:
        - mattermost
        - credentials-repo
        - credentials-integreat
      requires:
        - bump_version
  - e2e_android:
      context:
        - mattermost
        - browserstack
      requires:
        - build_android_integreat-e2e
  - deliver_android:
      matrix:
        parameters:
          build_config_name: [integreat, malte, aschaffenburg]
      context:
        - mattermost
        - browserstack
        - tuerantuer-google-play
      production_delivery: true
      requires:
        - check
        - e2e_android
        - build_android_<< matrix.build_config_name >>
  - sentry_android:
      context:
        - mattermost
        - sentry
      requires:
        - build_android
  - notify_android:
      context:
        - mattermost
        - deliverino
      production_delivery: true
      requires:
        - deliver_android

  - build_ios:
      name: build_ios_<< matrix.build_config_name >>
      matrix:
        parameters:
          build_config_name: [integreat-e2e, integreat, malte, aschaffenburg]
      context:
        - mattermost
        - tuerantuer-apple
        - fastlane-match
      requires:
        - bump_version
  - e2e_ios:
      context:
        - mattermost
        - browserstack
      requires:
        - build_ios_integreat-e2e
  - deliver_ios:
      matrix:
        parameters:
          build_config_name: [integreat, malte, aschaffenburg]
      context:
        - mattermost
        - browserstack
        - tuerantuer-apple
      production_delivery: true
      requires:
        - check
        - e2e_ios
        - build_ios_<< matrix.build_config_name >>
  - sentry_ios:
      context:
        - mattermost
        - sentry
      requires:
        - build_ios
  - notify_ios:
      context:
        - mattermost
        - deliverino
      production_delivery: true
      requires:
        - deliver_ios
